abaslib/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('ab4sl1b-admin-page/', admin.site.urls),
    path('', include('reader.urls')),
    path('', include('catalog.urls')),
    path('', include('titles.urls')),
    path('', include('ratings.urls')),
    path('', include('metadata.urls')),
    path('', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views


app_name = 'main'

urlpatterns = [
    path('',
        views.home_view,
        name='home'
        ),
    path(
        'title/<int:title_id>/',
        views.title_page_view,
        name='title_page'
        ),
    path('about_rights/',
        TemplateView.as_view(template_name="main/about_rights.html"),
        name='about_rights'
        ),
    path('title/<int:title_id>/add-to-favorites/',
        views.change_favorite_title_status,
        name='change_favorite_status'
        ),
    path(
        'titles/',
        views.all_titles_view,
        name='all_titles'
        ),
    path(
        'text/',
        views.text_titles_view,
        name='text_titles'
        ),
    path(
        'graphic/',
        views.graphic_titles_view,
        name='graphic_titles'
        )
]

reader/urls.py
from django.urls import path
from . import views


app_name = 'reader'

urlpatterns = [
    path('title/<int:title_id>/read/type=t/',
         views.read_text_title_view,
         name='read_text'),
    path('title/<int:title_id>/read/type=g/',
         views.read_graphic_title_view,
         name='read_graphic'),
    path('title/<int:title_id>/read/type=t/start/',
         views.start_read_text_view,
         name='start_read_text'),
    path('title/<int:title_id>/read/type=g/start/',
         views.start_read_graphic_view,
         name='start_read_graphic'),
    path('title/<int:title_id>/read/manage_bookmark/<int:chapter_id>/',
         views.manage_bookmark_view,
         name='manage_bookmark'),
    path('title/<int:title_id>/read/bookmark/',
         views.open_bookmark_view,
         name='open_bookmark')
]

titles/urls.py
from django.urls import path
from . import views


app_name = 'titles'

urlpatterns = [
    path(
        'upload_title/',
        views.upload_title_view,
        name='upload_title'
        ),
    path(
        'delete_title/title=<int:title_id>/',
        views.delete_title_view,
        name='delete_title'
        ),   
    path(
        'update_title/title=<int:title_id>/',
        views.update_title_view,
        name='update_title'
        ),
    path(
        'upload_chapter/title=<int:title_id>/',
        views.upload_chapter_view,
        name='upload_chapter'
        ),
    path(
        'delete_chapter/title=<int:title_id>/',
        views.delete_chapter_view,
        name='delete_chapter'
        ),
]

users/urls.py
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
    path('login/', views.login_user_view, name='login'),
    path('logout/', views.logout_user_view, name='logout'),
    path('register/', views.register_user_view, name='register'),
    path('user_profile/', views.user_profile_view, name='profile'),
    path('user_profile/<int:user_id>', views.another_user_profile_view, name='another_profile')
]

main/views.py
"""Views for 'main' app, pages with content"""
from itertools import chain
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.contenttypes.models import ContentType
from metadata.models import TitleView, TitleFavorite
from metadata.forms import FilterTagForm
from titles.models import TextTitle, GraphicTitle
from titles.utils import get_new_titles, get_updated_titles
from ratings.models import TitleRating
from . utils import redirect_to_title_page


# create views here.
def home_view(request):
    """Renders website's home page"""
    
    context = {
        'new_titles': get_new_titles(),
        'updated_titles': get_updated_titles()
        }
    return render(request, 'main/home.html', context)


def all_titles_view(request):
    """Renders page with all titles"""
    filter_form = FilterTagForm(request.GET)
    text_titles = TextTitle.objects.all()
    graphic_titles = GraphicTitle.objects.all()
    
    if filter_form.is_valid():
        genres = filter_form.cleaned_data.get('genres')
        tags = filter_form.cleaned_data.get('tags')
        
        if genres:
            text_titles = TextTitle.objects.filter(genres__tag_genre__in=genres).distinct()
            graphic_titles = GraphicTitle.objects.filter(genres__tag_genre__in=genres).distinct()
        if tags:
            text_titles = TextTitle.objects.filter(tags__tag__in=tags).distinct()
            graphic_titles = GraphicTitle.objects.filter(tags__tag__in=tags).distinct()
            
    titles = sorted(
        chain(text_titles, graphic_titles),
        key=lambda title: title.added_at,
        reverse=True
    )
            
    context = {
        'titles': titles,
        'filter_form': filter_form
    }
    return render(request, 'main/all_titles.html', context)


def text_titles_view(request):
    """Renders page with text titles"""
    filter_form = FilterTagForm(request.GET)
    text_titles = TextTitle.objects.all()
    
    if filter_form.is_valid():
        genres = filter_form.cleaned_data.get('genres')
        tags = filter_form.cleaned_data.get('tags')
        
        if genres:
            text_titles = TextTitle.objects.filter(genres__tag_genre__in=genres).distinct()
        if tags:
            text_titles = TextTitle.objects.filter(tags__tag__in=tags).distinct()
    
    context = {
        'text_titles': text_titles,
        'filter_form': filter_form
    }
    return render(request, 'main/text_titles.html', context)


def graphic_titles_view(request):
    """Renders page with graphic titles"""
    filter_form = FilterTagForm(request.GET)
    graphic_titles = GraphicTitle.objects.all()
    
    if filter_form.is_valid():
        genres = filter_form.cleaned_data.get('genres')
        tags = filter_form.cleaned_data.get('tags')
        
        if genres:
            graphic_titles = graphic_titles.filter(genres__tag_genre__in=genres).distinct()
        if tags:
            graphic_titles = graphic_titles.filter(tags__tag__in=tags).distinct()
            
    context = {
        'graphic_titles': graphic_titles,
        'filter_form': filter_form
    }
    return render(request, 'main/graphic_titles.html', context)


def collect_about_section(request, title_type, title_id):
    """Creates context for about section of title's page"""
    assert title_type in ['text', 'graphic']

    if title_type == 'graphic':
        title = get_object_or_404(GraphicTitle, id=title_id)
    elif title_type == 'text':
        title = get_object_or_404(TextTitle, id=title_id)
        
    # collect and update stats
    
    # metadata
    title.views_count = TitleView.get_views_count(title)
    title.favorites_count = TitleFavorite.get_favorite_count(title)
    title.save()
    is_favorite = TitleFavorite.get_favorite_status(title, request.user)
    tags = [relation.tag for relation in title.tags.all()]
    genres = [relation.tag_genre for relation in title.genres.all()]
    
    # ratings
    average_rate = TitleRating.get_average_rate(title)
    if request.user.is_authenticated:
        user_rate = title.ratings.filter(user=request.user).first()
    else:
        user_rate = 0
    
    user_rate = user_rate.rate if user_rate else 0
    rates_count = TitleRating.get_rates_count(title)

    context = {
        'title': title,
        'title_type': title_type,
        'user_favorite': is_favorite,
        'tags': tags,
        'genres': genres,
        'average_rate': average_rate,
        'rates_count': rates_count,
        'user_rate': user_rate
    }

    return context, 'main/title_page_about.html'


def collect_chapters_section(request, title_type, title_id):
    """Creates context for chapters section of title's page"""
    assert title_type in ['text', 'graphic']

    if title_type == 'graphic':
        title = get_object_or_404(GraphicTitle, id=title_id)
        chapters = title.graphic_chapters.all()
    elif title_type == 'text':
        title = get_object_or_404(TextTitle, id=title_id)
        chapters = title.text_chapters.all()

    is_favorite = TitleFavorite.get_favorite_status(title, request.user)

    context = {
        'title': title,
        'chapters': chapters,
        'title_type': title_type,
        'user_favorite': is_favorite
    }

    return context, 'main/title_page_chapters.html'


def collect_comment_section(request, title_type, title_id):
    """Creates context for comment section of title's page"""
    assert title_type in ['text', 'graphic']

    if title_type == 'graphic':
        title = get_object_or_404(GraphicTitle, id=title_id)
    elif title_type == 'text':
        title = get_object_or_404(TextTitle, id=title_id)

    is_favorite = TitleFavorite.get_favorite_status(title, request.user)

    if title:
        context = {
            'title': title,
            'title_type': title_type,
            'user_favorite': is_favorite
        }
    else:
        context = {}

    return context, 'main/title_page_comments.html'


def title_page_view(request, title_id=None):
    """Renders title page with specific context"""
    section = request.GET.get('section')
    title_type = request.GET.get('title_type')

    # collect context for different sections
    assert section in ['about', 'chapters', 'comments']

    if section == 'about':
        context, template = collect_about_section(request, title_type, title_id)
    elif section == 'chapters':
        context, template = collect_chapters_section(request, title_type, title_id)
    elif section == 'comments':
        context, template = collect_comment_section(request, title_type, title_id)
    
    return render(request, template, context)


@login_required(login_url="users:login")
def change_favorite_title_status(request, title_id=None):
    """
    Changes 'favorite' status of title for users when they press the button
    on title page
    """
    title_type = request.GET.get('title_type')
    user = request.user

    assert title_type in ['text', 'graphic']

    if title_type == 'graphic':
        title = get_object_or_404(GraphicTitle, id=title_id)
    elif title_type == 'text':
        title = get_object_or_404(TextTitle, id=title_id)
        
    content_type = ContentType.objects.get_for_model(title)
        
    if TitleFavorite.get_favorite_status(title, user):
        user.remove_title_from_favorites(title)
        TitleFavorite.objects.filter(
            user=user, 
            content_type=content_type,
            object_id=title_id).delete()
    else:
        user.add_title_to_favorites(title)
        TitleFavorite.objects.create(
            user=user,
            content_object=title,
        )

    return redirect_to_title_page(title_id, title_type, request.GET.get('section'))

templates/main/all_titles.html
{% extends 'main/home.html' %}
{% load static %}

{% block title %}
  ABASlib — Всё и сразу
{% endblock %}

{% block titles %}
  <h4>Тайтлы</h4>
  {% if not titles %}
    <p class="highlighted_text centered">Подходящие тайтлы не найдены</p>
  {% endif %}
  <div class="titles">
    {% for title in titles %}
      <a title="{{ title.title_name_rus }}" class="title_card" href="{% url 'main:title_page' title.id %}?title_type={{ title.title_type }}&section=about">
        <img class="cover" src="{{ title.title_cover.url }}" alt="Здесь была обложка" />
        <div class="title_name">{{ title.title_name_rus }}</div>
      </a>
    {% endfor %}
  </div>
{% endblock %}

{% block sections %}
  <section>
    <h1>Разделы</h1>
    <a href="{% url 'main:home' %}"><button class="ref_button">Главная</button></a>
    <a href="{% url 'main:all_titles' %}"><button class="ref_button activated">Все тайтлы</button></a>
    <a href="{% url 'main:text_titles' %}"><button class="ref_button">Новеллы</button></a>
    <a href="{% url 'main:graphic_titles' %}"><button class="ref_button">Комиксы</button></a>
  </section>
{% endblock %}

{% block filters %}
  <section>
    <h1>Фильтры</h1>
    <a href="{% url 'main:all_titles' %}">
      <button class="filter_button">
        Сбросить фильтры
      </button>
    </a>
    <button type="submit" form="filter_form" class="filter_button">
      Применить фильтры
    </button>
    <form id="filter_form" action="{% url 'main:all_titles' %}" method="get">      
      <h4>Жанры</h4>
      <ul class="filter_list">
        {% for checkbox in filter_form.genres %}
          <li>
            <label>
              {{ checkbox.tag }} 
              <span class="filter_button">{{ checkbox.choice_label }}</span>
            </label>
          </li>
        {% endfor %}
      </ul>
  
      <h4>Тэги</h4>
      <ul class="filter_list">
        {% for checkbox in filter_form.tags %}
          <li>
            <label>
              {{ checkbox.tag }} 
              <span class="filter_button">{{ checkbox.choice_label }}</span>
            </label>
          </li>
        {% endfor %}
      </ul>
    </form>
  </section>
{% endblock %}

templates/main/graphic_titles.html
{% extends 'main/home.html' %}
{% load static %}

{% block title %}
  ABASlib — Комиксы
{% endblock %}

{% block titles %}
  <h4>Комиксы</h4>
  {% if not graphic_titles %}
    <p class="highlighted_text centered">Подходящие тайтлы не найдены</p>
  {% endif %}
  <div class="titles">
    {% for title in graphic_titles %}
      <a title="{{ title.title_name_rus }}" class="title_card" href="{% url 'main:title_page' title.id %}?title_type={{ title.title_type }}&section=about">
        <img class="cover" src="{{ title.title_cover.url }}" alt="Здесь была обложка" />
        <div class="title_name">{{ title.title_name_rus }}</div>
      </a>
    {% endfor %}
  </div>
{% endblock %}

{% block sections %}
  <section>
    <h1>Разделы</h1>
    <a href="{% url 'main:home' %}"><button class="ref_button">Главная</button></a>
    <a href="{% url 'main:all_titles' %}"><button class="ref_button">Все тайтлы</button></a>
    <a href="{% url 'main:text_titles' %}"><button class="ref_button">Новеллы</button></a>
    <a href="{% url 'main:graphic_titles' %}"><button class="ref_button activated">Комиксы</button></a>
  </section>
{% endblock %}

{% block filters %}
  <section>
    <h1>Фильтры</h1>
    <a href="{% url 'main:graphic_titles' %}">
      <button class="filter_button">
        Сбросить фильтры
      </button>
    </a>
    <button type="submit" form="filter_form" class="filter_button">
      Применить фильтры
    </button>
    <form id="filter_form" action="{% url 'main:graphic_titles' %}" method="get">      
      <h4>Жанры</h4>
      <ul class="filter_list">
        {% for checkbox in filter_form.genres %}
          <li>
            <label>
              {{ checkbox.tag }} 
              <span class="filter_button">{{ checkbox.choice_label }}</span>
            </label>
          </li>
        {% endfor %}
      </ul>
  
      <h4>Тэги</h4>
      <ul class="filter_list">
        {% for checkbox in filter_form.tags %}
          <li>
            <label>
              {{ checkbox.tag }} 
              <span class="filter_button">{{ checkbox.choice_label }}</span>
            </label>
          </li>
        {% endfor %}
      </ul>
    </form>
  </section>
{% endblock %}

templates/main/home.html
<!-- Homepage of ABASlib -->
{% extends 'base.html' %}
{% load static %}
{% block title %}
  ABASlib — Главная
{% endblock %}

{% block styles %}
  <link rel="stylesheet" href="{% static 'css\main\home_styles.css' %}" />
{% endblock %}

{% block header %}
  {% block search %}
    <form id="search" action="{% url 'search:search_by_name' %}" method="get">
      {% csrf_token %}
      <input
        id="search_input"
        type="search"
        name="search_field"
        placeholder="Поиск"
      />
    </form>
  {% endblock %}

  <div class="button_group">
    {% if user.is_authenticated %}
      <div class="custom_select">
        <select name="redact_options" onchange="location = this.value" class="ref_button">
          <option selected hidden disabled>Меню</option>
          <option value="{% url 'titles:upload_title' %}?title_type=text">Добавить тайтл (текст)</option>
          <option value="{% url 'titles:upload_title' %}?title_type=graphic">Добавить тайтл (графика)</option>
          {% block redact_options %}

          {% endblock %}
        </select>
      </div>
      <a id="profile_link" href="{% url 'users:profile' %}">
        <button class="ref_button">
          <img id="user_pic" src="{{ user.user_avatar.url }}" />
          {{ user.username }}
        </button>
      </a>
      <a id="logout_link" href="{% url 'users:logout' %}">
        <button class="ref_button">
          <svg xmlns="http://www.w3.org/2000/svg" class="button_icon" fill="currentColor" class="bi bi-box-arrow-left" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M6 12.5a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v2a.5.5 0 0 1-1 0v-2A1.5 1.5 0 0 1 6.5 2h8A1.5 1.5 0 0 1 16 3.5v9a1.5 1.5 0 0 1-1.5 1.5h-8A1.5 1.5 0 0 1 5 12.5v-2a.5.5 0 0 1 1 0z" />
            <path fill-rule="evenodd" d="M.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L1.707 7.5H10.5a.5.5 0 0 1 0 1H1.707l2.147 2.146a.5.5 0 0 1-.708.708z" />
          </svg>Выход
        </button>
      </a>
    {% else %}
      <a id="login_link" href="{% url 'users:login' %}">
        <button class="ref_button">
          <svg xmlns="http://www.w3.org/2000/svg" class="button_icon" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0z" />
            <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z" />
          </svg>Авторизация
        </button>
      </a>
    {% endif %}
  </div>
{% endblock %}

{% block content %}
  <div class="container">
    <div id="main_content">
      <h1>ABASlib</h1>
      <hr />
      {% block titles %}
        <h4>Недавно добавлено</h4>
        <div class="titles">
          {% for title in new_titles %}
            <a title="{{ title.title_name_rus }}" class="title_card" href="{% url 'main:title_page' title.id %}?title_type={{ title.title_type }}&section=about">
              <img class="cover" src="{{ title.title_cover.url }}" alt="Здесь была обложка" />
              <div class="title_name">{{ title.title_name_rus }}</div>
            </a>
          {% endfor %}
        </div>
        <h4>Обновления</h4>
        <div class="titles">
          {% for title in updated_titles %}
            <a title="{{ title.title_name_rus }}" class="title_card" href="{% url 'main:title_page' title.id %}?title_type={{ title.title_type }}&section=about">
              <img class="cover" src="{{ title.title_cover.url }}" alt="Здесь была обложка" />
              <div class="title_name">{{ title.title_name_rus }}</div>
            </a>
          {% endfor %}
        </div>
      {% endblock %}
    </div>

    <div id="side">
      {% block sections %}
        <section>
          <h1>Разделы</h1>
          <a href="{% url 'main:home' %}"><button class="ref_button activated">Главная</button></a>
          <a href="{% url 'main:all_titles' %}"><button class="ref_button">Все тайтлы</button></a>
          <a href="{% url 'main:text_titles' %}"><button class="ref_button">Новеллы</button></a>
          <a href="{% url 'main:graphic_titles' %}"><button class="ref_button">Комиксы</button></a>
        </section>
      {% endblock %}
      
      {% block filters %}
      
      {% endblock %}

    </div>
  </div>
{% endblock %}

templates/main/text_titles.html
{% extends 'main/home.html' %}
{% load static %}

{% block title %}
  ABASlib — Новеллы
{% endblock %}

{% block titles %}
  <h4>Новеллы</h4>
  {% if not text_titles %}
    <p class="highlighted_text centered">Подходящие тайтлы не найдены</p>
  {% endif %}
  <div class="titles">
    {% for title in text_titles %}
      <a title="{{ title.title_name_rus }}" class="title_card" href="{% url 'main:title_page' title.id %}?title_type={{ title.title_type }}&section=about">
        <img class="cover" src="{{ title.title_cover.url }}" alt="Здесь была обложка" />
        <div class="title_name">{{ title.title_name_rus }}</div>
      </a>
    {% endfor %}
  </div>
{% endblock %}

{% block sections %}
  <section>
    <h1>Разделы</h1>
    <a href="{% url 'main:home' %}"><button class="ref_button">Главная</button></a>
    <a href="{% url 'main:text_titles' %}"><button class="ref_button activated">Новеллы</button></a>
    <a href="{% url 'main:graphic_titles' %}"><button class="ref_button">Комиксы</button></a>
  </section>
{% endblock %}

{% block filters %}
  <section>
    <h1>Фильтры</h1>
    <a href="{% url 'main:text_titles' %}">
      <button class="filter_button">
        Сбросить фильтры
      </button>
    </a>
    <button type="submit" form="filter_form" class="filter_button">
      Применить фильтры
    </button>
    <form id="filter_form" action="{% url 'main:text_titles' %}" method="get">      
      <h4>Жанры</h4>
      <ul class="filter_list">
        {% for checkbox in form.genres %}
          <li>
            <label>
              {{ checkbox.tag }} 
              <span class="filter_button">{{ checkbox.choice_label }}</span>
            </label>
          </li>
        {% endfor %}
      </ul>
  
      <h4>Тэги</h4>
      <ul class="filter_list">
        {% for checkbox in form.tags %}
          <li>
            <label>
              {{ checkbox.tag }} 
              <span class="filter_button">{{ checkbox.choice_label }}</span>
            </label>
          </li>
        {% endfor %}
      </ul>
    </form>
  </section>
{% endblock %}

templates/main/title_page_chapters.html
{% extends 'main/title_page_base.html' %}
{% load static %}

{% block sections %}
  <a href="{% url 'main:title_page' title.id %}?title_type={{ request.GET.title_type }}&section=about">
    <button class="ref_button">
      <svg xmlns="http://www.w3.org/2000/svg" class="button_icon" fill="currentColor" class="bi bi-info-square" viewBox="0 0 16 16">
        <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2z" />
        <path d="m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0" />
      </svg>О тайтле
    </button>
  </a>
  <button class="ref_button activated">
    <svg xmlns="http://www.w3.org/2000/svg" class="button_icon" fill="currentColor" class="bi bi-journal" viewBox="0 0 16 16">
      <path d="M3 0h10a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-1h1v1a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1v1H1V2a2 2 0 0 1 2-2" />
      <path d="M1 5v-.5a.5.5 0 0 1 1 0V5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1zm0 3v-.5a.5.5 0 0 1 1 0V8h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1zm0 3v-.5a.5.5 0 0 1 1 0v.5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1z" />
    </svg>Главы
  </button>
  <a href="{% url 'main:title_page' title.id %}?title_type={{ request.GET.title_type }}&section=comments">
    <button class="ref_button">
      <svg xmlns="http://www.w3.org/2000/svg" class="button_icon" fill="currentColor" class="bi bi-chat-square-text" viewBox="0 0 16 16">
        <path d="M14 1a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1h-2.5a2 2 0 0 0-1.6.8L8 14.333 6.1 11.8a2 2 0 0 0-1.6-.8H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1zM2 0a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2.5a1 1 0 0 1 .8.4l1.9 2.533a1 1 0 0 0 1.6 0l1.9-2.533a1 1 0 0 1 .8-.4H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2z" />
        <path d="M3 3.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5M3 6a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9A.5.5 0 0 1 3 6m0 2.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5" />
      </svg>Комментарии
    </button>
  </a>
{% endblock %}

{% block section %}
  <!-- CHAPTERS SECTION -->
  {% if not chapters %}
    <p>Кажется, главы еще не загрузили</p>
  {% endif %}
  <div id="chapters">
    {% for chapter in chapters %}
      {% if not chapter.is_empty %}
        <div class="button_group">
          {% if request.GET.title_type == 'graphic' %}
            <a href="">
              <button class="ref_button">
                <svg xmlns="http://www.w3.org/2000/svg" class="button_icon" fill="currentColor" class="bi bi-bookmark" viewBox="0 0 16 16">
                  <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1z" />
                </svg>
              </button>
            </a>
            <a href="{% url 'reader:read_graphic' title.id %}?chapter_num={{ chapter.chapter_number }}&page=1"><button class="ref_button">{{ chapter }}</button></a>
          {% else %}
            <a href="">
              <button class="ref_button">
                <svg xmlns="http://www.w3.org/2000/svg" class="button_icon" fill="currentColor" class="bi bi-bookmark" viewBox="0 0 16 16">
                  <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1z" />
                </svg>
              </button>
            </a>
            <a href="{% url 'reader:read_text' title.id %}?chapter_num={{ chapter.chapter_number }}"><button class="ref_button">{{ chapter }}</button></a>
          {% endif %}
        </div>
      {% endif %}
    {% endfor %}
  </div>
{% endblock %}