abaslib/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('ab4sl1b-admin-page/', admin.site.urls),
    path('', include('reader.urls')),
    path('', include('catalog.urls')),
    path('', include('titles.urls')),
    path('', include('ratings.urls')),
    path('', include('metadata.urls')),
    path('', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views


app_name = 'catalog'

urlpatterns = [
    path('',
        views.home_view,
        name='home'
        ),
    path(
        'title/<int:title_id>/',
        views.title_page_view,
        name='title_page'
        ),
    path('about_rights/',
        TemplateView.as_view(template_name="catalog/about_rights.html"),
        name='about_rights'
        ),
    path(
        'titles/all/',
        views.all_titles_view,
        name='all_titles'
        ),
    path(
        'titles/text/',
        views.text_titles_view,
        name='text_titles'
        ),
    path(
        'titles/graphic/',
        views.graphic_titles_view,
        name='graphic_titles'
        )
]

main/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views


app_name = 'main'

urlpatterns = [
    path('',
        views.home_view,
        name='home'
        ),
    path(
        'title/<int:title_id>/',
        views.title_page_view,
        name='title_page'
        ),
    path('about_rights/',
        TemplateView.as_view(template_name="main/about_rights.html"),
        name='about_rights'
        ),
    path('title/<int:title_id>/add-to-favorites/',
        views.change_favorite_title_status,
        name='change_favorite_status'
        ),
    path(
        'titles/',
        views.all_titles_view,
        name='all_titles'
        ),
    path(
        'text/',
        views.text_titles_view,
        name='text_titles'
        ),
    path(
        'graphic/',
        views.graphic_titles_view,
        name='graphic_titles'
        )
]

templates/base.html
<!-- Base for html files -->
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8" />
    <meta name="author" content="withered" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicon/apple-touch-icon.png' %}" />
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon/favicon-32x32.png' %}" />
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon/favicon-16x16.png' %}" />
    <link rel="manifest" href="{% static 'images/favicon/site.webmanifest' %}" />
    <title>
      {% block title %}
        ABASlib
      {% endblock %}
    </title>

    <link rel="stylesheet" href="{% static 'css/variables.css' %}">
    <link rel="stylesheet" href="{% static 'css/base_styles.css' %}" />
    {% block styles %}

    {% endblock %}
  </head>

  <body>
    <header>
      <div id="header-container">
        <div id="site-icon">
          <a class="a-button block-button" href="{% url 'catalog:home' %}">
            <img id="icon" src="{% static 'images/favicon/android-chrome-192x192.png' %}" />ABASlib
          </a>
        </div>
        <div id="header-buttons">
          {% block header %}
  
          {% endblock %}
        </div>
      </div>
    </header>

    {% block content %}

    {% endblock %}

    <footer>
      <div id="footer-container">
        <p>
          2025 - {% now 'Y' %}
        </p>
        <div>
        <div>
          {% block footer %}
  
          {% endblock %}
        </div>
        <a class="a-button block-button" href="{% url 'catalog:about_rights' %}">
          Для правообладателей
        </a>
      </div>
    </footer>
    
    {% block scripts %}

    {% endblock %}
  </body>
</html>