abaslib/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('ab4sl1b-admin-page/', admin.site.urls),
    path('', include('reader.urls')),
    path('', include('catalog.urls')),
    path('', include('titles.urls')),
    path('', include('ratings.urls')),
    path('', include('metadata.urls')),
    path('', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views


app_name = 'main'

urlpatterns = [
    path('',
        views.home_view,
        name='home'
        ),
    path(
        'title/<int:title_id>/',
        views.title_page_view,
        name='title_page'
        ),
    path('about_rights/',
        TemplateView.as_view(template_name="main/about_rights.html"),
        name='about_rights'
        ),
    path('title/<int:title_id>/add-to-favorites/',
        views.change_favorite_title_status,
        name='change_favorite_status'
        ),
    path(
        'titles/',
        views.all_titles_view,
        name='all_titles'
        ),
    path(
        'text/',
        views.text_titles_view,
        name='text_titles'
        ),
    path(
        'graphic/',
        views.graphic_titles_view,
        name='graphic_titles'
        )
]

titles/urls.py
from django.urls import path
from . import views


app_name = 'titles'

urlpatterns = [
    path(
        'upload_title/',
        views.upload_title_view,
        name='upload_title'
        ),
    path(
        'delete_title/title=<int:title_id>/',
        views.delete_title_view,
        name='delete_title'
        ),   
    path(
        'update_title/title=<int:title_id>/',
        views.update_title_view,
        name='update_title'
        ),
    path(
        'upload_chapter/title=<int:title_id>/',
        views.upload_chapter_view,
        name='upload_chapter'
        ),
    path(
        'delete_chapter/title=<int:title_id>/',
        views.delete_chapter_view,
        name='delete_chapter'
        ),
]

users/urls.py
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
    path('login/', views.login_user_view, name='login'),
    path('logout/', views.logout_user_view, name='logout'),
    path('register/', views.register_user_view, name='register'),
    path('user_profile/', views.user_profile_view, name='profile'),
    path('user_profile/<int:user_id>', views.another_user_profile_view, name='another_profile')
]

main/views.py
"""Views for 'main' app, pages with content"""
from itertools import chain
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.contenttypes.models import ContentType
from metadata.models import TitleView, TitleFavorite
from metadata.forms import FilterTagForm
from titles.models import TextTitle, GraphicTitle
from titles.utils import get_new_titles, get_updated_titles
from ratings.models import TitleRating
from . utils import redirect_to_title_page


# create views here.
def home_view(request):
    """Renders website's home page"""
    
    context = {
        'new_titles': get_new_titles(),
        'updated_titles': get_updated_titles()
        }
    return render(request, 'main/home.html', context)


def all_titles_view(request):
    """Renders page with all titles"""
    filter_form = FilterTagForm(request.GET)
    text_titles = TextTitle.objects.all()
    graphic_titles = GraphicTitle.objects.all()
    
    if filter_form.is_valid():
        genres = filter_form.cleaned_data.get('genres')
        tags = filter_form.cleaned_data.get('tags')
        
        if genres:
            text_titles = TextTitle.objects.filter(genres__tag_genre__in=genres).distinct()
            graphic_titles = GraphicTitle.objects.filter(genres__tag_genre__in=genres).distinct()
        if tags:
            text_titles = TextTitle.objects.filter(tags__tag__in=tags).distinct()
            graphic_titles = GraphicTitle.objects.filter(tags__tag__in=tags).distinct()
            
    titles = sorted(
        chain(text_titles, graphic_titles),
        key=lambda title: title.added_at,
        reverse=True
    )
            
    context = {
        'titles': titles,
        'filter_form': filter_form
    }
    return render(request, 'main/all_titles.html', context)


def text_titles_view(request):
    """Renders page with text titles"""
    filter_form = FilterTagForm(request.GET)
    text_titles = TextTitle.objects.all()
    
    if filter_form.is_valid():
        genres = filter_form.cleaned_data.get('genres')
        tags = filter_form.cleaned_data.get('tags')
        
        if genres:
            text_titles = TextTitle.objects.filter(genres__tag_genre__in=genres).distinct()
        if tags:
            text_titles = TextTitle.objects.filter(tags__tag__in=tags).distinct()
    
    context = {
        'text_titles': text_titles,
        'filter_form': filter_form
    }
    return render(request, 'main/text_titles.html', context)


def graphic_titles_view(request):
    """Renders page with graphic titles"""
    filter_form = FilterTagForm(request.GET)
    graphic_titles = GraphicTitle.objects.all()
    
    if filter_form.is_valid():
        genres = filter_form.cleaned_data.get('genres')
        tags = filter_form.cleaned_data.get('tags')
        
        if genres:
            graphic_titles = graphic_titles.filter(genres__tag_genre__in=genres).distinct()
        if tags:
            graphic_titles = graphic_titles.filter(tags__tag__in=tags).distinct()
            
    context = {
        'graphic_titles': graphic_titles,
        'filter_form': filter_form
    }
    return render(request, 'main/graphic_titles.html', context)


def collect_about_section(request, title_type, title_id):
    """Creates context for about section of title's page"""
    assert title_type in ['text', 'graphic']

    if title_type == 'graphic':
        title = get_object_or_404(GraphicTitle, id=title_id)
    elif title_type == 'text':
        title = get_object_or_404(TextTitle, id=title_id)
        
    # collect and update stats
    
    # metadata
    title.views_count = TitleView.get_views_count(title)
    title.favorites_count = TitleFavorite.get_favorite_count(title)
    title.save()
    is_favorite = TitleFavorite.get_favorite_status(title, request.user)
    tags = [relation.tag for relation in title.tags.all()]
    genres = [relation.tag_genre for relation in title.genres.all()]
    
    # ratings
    average_rate = TitleRating.get_average_rate(title)
    if request.user.is_authenticated:
        user_rate = title.ratings.filter(user=request.user).first()
    else:
        user_rate = 0
    
    user_rate = user_rate.rate if user_rate else 0
    rates_count = TitleRating.get_rates_count(title)

    context = {
        'title': title,
        'title_type': title_type,
        'user_favorite': is_favorite,
        'tags': tags,
        'genres': genres,
        'average_rate': average_rate,
        'rates_count': rates_count,
        'user_rate': user_rate
    }

    return context, 'main/title_page_about.html'


def collect_chapters_section(request, title_type, title_id):
    """Creates context for chapters section of title's page"""
    assert title_type in ['text', 'graphic']

    if title_type == 'graphic':
        title = get_object_or_404(GraphicTitle, id=title_id)
        chapters = title.graphic_chapters.all()
    elif title_type == 'text':
        title = get_object_or_404(TextTitle, id=title_id)
        chapters = title.text_chapters.all()

    is_favorite = TitleFavorite.get_favorite_status(title, request.user)

    context = {
        'title': title,
        'chapters': chapters,
        'title_type': title_type,
        'user_favorite': is_favorite
    }

    return context, 'main/title_page_chapters.html'


def collect_comment_section(request, title_type, title_id):
    """Creates context for comment section of title's page"""
    assert title_type in ['text', 'graphic']

    if title_type == 'graphic':
        title = get_object_or_404(GraphicTitle, id=title_id)
    elif title_type == 'text':
        title = get_object_or_404(TextTitle, id=title_id)

    is_favorite = TitleFavorite.get_favorite_status(title, request.user)

    if title:
        context = {
            'title': title,
            'title_type': title_type,
            'user_favorite': is_favorite
        }
    else:
        context = {}

    return context, 'main/title_page_comments.html'


def title_page_view(request, title_id=None):
    """Renders title page with specific context"""
    section = request.GET.get('section')
    title_type = request.GET.get('title_type')

    # collect context for different sections
    assert section in ['about', 'chapters', 'comments']

    if section == 'about':
        context, template = collect_about_section(request, title_type, title_id)
    elif section == 'chapters':
        context, template = collect_chapters_section(request, title_type, title_id)
    elif section == 'comments':
        context, template = collect_comment_section(request, title_type, title_id)
    
    return render(request, template, context)


@login_required(login_url="users:login")
def change_favorite_title_status(request, title_id=None):
    """
    Changes 'favorite' status of title for users when they press the button
    on title page
    """
    title_type = request.GET.get('title_type')
    user = request.user

    assert title_type in ['text', 'graphic']

    if title_type == 'graphic':
        title = get_object_or_404(GraphicTitle, id=title_id)
    elif title_type == 'text':
        title = get_object_or_404(TextTitle, id=title_id)
        
    content_type = ContentType.objects.get_for_model(title)
        
    if TitleFavorite.get_favorite_status(title, user):
        user.remove_title_from_favorites(title)
        TitleFavorite.objects.filter(
            user=user, 
            content_type=content_type,
            object_id=title_id).delete()
    else:
        user.add_title_to_favorites(title)
        TitleFavorite.objects.create(
            user=user,
            content_object=title,
        )

    return redirect_to_title_page(title_id, title_type, request.GET.get('section'))

main/templates/main/home.html
<!-- Homepage of ABASlib -->
{% extends 'main/base.html' %}
{% load static %}
{% block title %}
  ABASlib — Главная
{% endblock %}

{% block styles %}
  <link rel="stylesheet" href="{% static 'css\main\home_styles.css' %}" />
{% endblock %}

{% block header %}
  <div class="button_group">
    {% if user.is_authenticated %}
        <div class="custom_select">
          <select name="redact_options" onchange="location = this.value" class="ref_button">
            <option selected hidden disabled>Меню редактора</option>
            <option value="{% url 'main:upload_title' %}?title_type=text">Добавить тайтл (текст)</option>
            <option value="{% url 'main:upload_title' %}?title_type=graphic">Добавить тайтл (графика)</option>
            {% block redact_options %}

            {% endblock %}
          </select>  
        </div>
        <a id="profile_link" href="{% url 'users:profile' %}">
          <button class="ref_button">
            <img id="user_pic" src="{{ user.user_avatar.url }}" />
              {{ user.username }}
            </button>
          </a>
        <a id="logout_link" href="{% url 'users:logout' %}">
          <button class="ref_button">
            <svg xmlns="http://www.w3.org/2000/svg" class="button_icon" fill="currentColor" class="bi bi-box-arrow-left" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M6 12.5a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v2a.5.5 0 0 1-1 0v-2A1.5 1.5 0 0 1 6.5 2h8A1.5 1.5 0 0 1 16 3.5v9a1.5 1.5 0 0 1-1.5 1.5h-8A1.5 1.5 0 0 1 5 12.5v-2a.5.5 0 0 1 1 0z"/>
              <path fill-rule="evenodd" d="M.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L1.707 7.5H10.5a.5.5 0 0 1 0 1H1.707l2.147 2.146a.5.5 0 0 1-.708.708z"/>
            </svg>
            Выход
          </button>
        </a>

    {% else %}
        <a id="login_link" href="{% url 'users:login' %}">
          <button class="ref_button">
            <svg xmlns="http://www.w3.org/2000/svg" class="button_icon" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0z"/>
              <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z"/>
            </svg>
            Авторизация
          </button>
        </a>
      </div>
    {% endif %}
  </div>
{% endblock %}

{% block content %}
  <div class="container">
    <div id="main_content">
      <h1>ABASlib</h1>
      <hr />
      <h4>Недавно добавлено</h4>
      <div class="titles">
        {% for title in new_titles %}
          <a title="{{ title.title_name_rus }}" class="title_card" href="{% url 'main:title_page' title.id %}?title_type={{ title.title_type }}&section=about">
              <img class="cover" src="{{ title.title_cover.url }}" alt="Здесь была обложка">
              <div class="title_name">{{ title.title_name_rus }}</div>
          </a>
        {% endfor %}
      </div>
      <h4>Обновления</h4>
      <div class="titles">
        {% for title in updated_titles %}
          <a title="{{ title.title_name_rus }}" class="title_card" href="{% url 'main:title_page' title.id %}?title_type={{ title.title_type }}&section=about">
              <img class="cover" src="{{ title.title_cover.url }}" alt="Здесь была обложка">
              <div class="title_name">{{ title.title_name_rus }}</div>
          </a>
        {% endfor %}
      </div>
    </div>

    <div id="side">
      <h1>Разделы</h1>
      <hr />
      <a href="{% url 'main:home' %}">
        <button class="ref_button activated">
          Главная
        </button>
      </a>
      <a href="{% url 'main:text_titles' %}">
        <button class="ref_button">
          Новеллы
        </button>
      </a>
      <a href="{% url 'main:graphic_titles' %}">
        <button class="ref_button">
          Комиксы
        </button>
      </a>
    </div>
  </div>
{% endblock %}