abaslib/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('ab4sl1b-admin-page/', admin.site.urls),
    path('', include('reader.urls')),
    path('', include('catalog.urls')),
    path('', include('titles.urls')),
    path('', include('ratings.urls')),
    path('', include('metadata.urls')),
    path('', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views


app_name = 'catalog'

urlpatterns = [
    path('',
        views.home_view,
        name='home'
        ),
    path(
        'title/<int:title_id>/',
        views.title_page_view,
        name='title_page'
        ),
    path('about_rights/',
        TemplateView.as_view(template_name="catalog/about_rights.html"),
        name='about_rights'
        ),
    path(
        'titles/all/',
        views.all_titles_view,
        name='all_titles'
        ),
    path(
        'titles/text/',
        views.text_titles_view,
        name='text_titles'
        ),
    path(
        'titles/graphic/',
        views.graphic_titles_view,
        name='graphic_titles'
        )
]

main/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views


app_name = 'main'

urlpatterns = [
    path('',
        views.home_view,
        name='home'
        ),
    path(
        'title/<int:title_id>/',
        views.title_page_view,
        name='title_page'
        ),
    path('about_rights/',
        TemplateView.as_view(template_name="main/about_rights.html"),
        name='about_rights'
        ),
    path('title/<int:title_id>/add-to-favorites/',
        views.change_favorite_title_status,
        name='change_favorite_status'
        ),
    path(
        'titles/',
        views.all_titles_view,
        name='all_titles'
        ),
    path(
        'text/',
        views.text_titles_view,
        name='text_titles'
        ),
    path(
        'graphic/',
        views.graphic_titles_view,
        name='graphic_titles'
        )
]

ratings/urls.py
from django.urls import path
from . import views


app_name = 'ratings'

urlpatterns = [
    path('rate/<str:title_type>/<int:title_id>/<int:rate>/',
         views.rate_title_view,
         name='rate_title'),
    path('rate/<str:title_type>/<int:title_id>/',
         views.delete_rate_title_view,
         name='delete_rate'),
]

reader/urls.py
from django.urls import path
from . import views


app_name = 'reader'

urlpatterns = [
    path('title/<int:title_id>/read/type=t/',
         views.read_text_title_view,
         name='read_text'),
    path('title/<int:title_id>/read/type=g/',
         views.read_graphic_title_view,
         name='read_graphic'),
    path('title/<int:title_id>/read/type=t/start/',
         views.start_read_text_view,
         name='start_read_text'),
    path('title/<int:title_id>/read/type=g/start/',
         views.start_read_graphic_view,
         name='start_read_graphic'),
    path('title/<int:title_id>/read/manage_bookmark/<int:chapter_id>/',
         views.manage_bookmark_view,
         name='manage_bookmark'),
    path('title/<int:title_id>/read/bookmark/',
         views.open_bookmark_view,
         name='open_bookmark')
]

titles/urls.py
from django.urls import path
from . import views


app_name = 'titles'

urlpatterns = [
    path(
        'upload_title/',
        views.upload_title_view,
        name='upload_title'
        ),
    path(
        'delete_title/title=<int:title_id>/',
        views.delete_title_view,
        name='delete_title'
        ),   
    path(
        'update_title/title=<int:title_id>/',
        views.update_title_view,
        name='update_title'
        ),
    path(
        'upload_chapter/title=<int:title_id>/',
        views.upload_chapter_view,
        name='upload_chapter'
        ),
    path(
        'delete_chapter/title=<int:title_id>/',
        views.delete_chapter_view,
        name='delete_chapter'
        ),
]

users/urls.py
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
    path('login/', views.login_user_view, name='login'),
    path('logout/', views.logout_user_view, name='logout'),
    path('register/', views.register_user_view, name='register'),
    path('user_profile/', views.user_profile_view, name='profile'),
    path('user_profile/<int:user_id>', views.another_user_profile_view, name='another_profile')
]

catalog/models.py
from django.db import models

# Create your models here.

catalog/views.py
"""Views for 'catalog' app, pages with content"""
from itertools import chain
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from metadata.models import TitleView, TitleFavorite
from metadata.forms import FilterTagForm
from titles.models import TextTitle, GraphicTitle
from titles.utils import get_new_titles, get_updated_titles
from ratings.models import TitleRating
from comments.forms import CommentForm
from reader.models import TextTitleBookmark, GraphicTitleBookmark
from .utils import redirect_to_title_page


# create views here.
def home_view(request):
    """Renders website's home page"""

    context = {
        'new_titles': get_new_titles(),
        'updated_titles': get_updated_titles()
        }
    return render(request, 'catalog/home.html', context)


def all_titles_view(request):
    """Renders page with all titles"""
    filter_form = FilterTagForm(request.GET)
    search_query = request.GET.get('search_query', None)

    text_titles = TextTitle.objects.all()
    graphic_titles = GraphicTitle.objects.all()

    # apply search query
    if search_query:
        text_titles = text_titles.filter(
            Q(title_name_rus__icontains=search_query) |
            Q(title_name_eng__icontains=search_query)
        )
        graphic_titles = graphic_titles.filter(
            Q(title_name_rus__icontains=search_query) |
            Q(title_name_eng__icontains=search_query)
        )

    # apply filters
    if filter_form.is_valid():
        genres = filter_form.cleaned_data.get('genres')
        tags = filter_form.cleaned_data.get('tags')

        if genres:
            text_titles = text_titles.filter(genres__tag_genre__in=genres).distinct()
            graphic_titles = graphic_titles.filter(genres__tag_genre__in=genres).distinct()
        if tags:
            text_titles = text_titles.filter(tags__tag__in=tags).distinct()
            graphic_titles = graphic_titles.filter(tags__tag__in=tags).distinct()

    titles = sorted(
        chain(text_titles, graphic_titles),
        key=lambda title: title.added_at,
        reverse=True
    )

    context = {
        'titles': titles,
        'filter_form': filter_form
    }
    return render(request, 'catalog/all_titles.html', context)


def text_titles_view(request):
    """Renders page with text titles"""
    filter_form = FilterTagForm(request.GET)
    search_query = request.GET.get('search_query', None)

    text_titles = TextTitle.objects.all()

    # apply search query
    if search_query:
        text_titles = text_titles.filter(
            Q(title_name_rus__icontains=search_query) |
            Q(title_name_eng__icontains=search_query)
        )

    if filter_form.is_valid():
        genres = filter_form.cleaned_data.get('genres')
        tags = filter_form.cleaned_data.get('tags')

        if genres:
            text_titles = text_titles.filter(genres__tag_genre__in=genres).distinct()
        if tags:
            text_titles = text_titles.filter(tags__tag__in=tags).distinct()

    context = {
        'text_titles': text_titles,
        'filter_form': filter_form
    }
    return render(request, 'catalog/text_titles.html', context)


def graphic_titles_view(request):
    """Renders page with graphic titles"""
    filter_form = FilterTagForm(request.GET)
    search_query = request.GET.get('search_query', None)

    graphic_titles = GraphicTitle.objects.all()

    # apply search query
    if search_query:
        graphic_titles = graphic_titles.filter(
            Q(title_name_rus__icontains=search_query) |
            Q(title_name_eng__icontains=search_query)
        )

    if filter_form.is_valid():
        genres = filter_form.cleaned_data.get('genres')
        tags = filter_form.cleaned_data.get('tags')

        if genres:
            graphic_titles = graphic_titles.filter(genres__tag_genre__in=genres).distinct()
        if tags:
            graphic_titles = graphic_titles.filter(tags__tag__in=tags).distinct()

    context = {
        'graphic_titles': graphic_titles,
        'filter_form': filter_form
    }
    return render(request, 'catalog/graphic_titles.html', context)


def collect_about_section(request, title_type, title_id):
    """Creates context for about section of title's page"""
    assert title_type in ['text', 'graphic']

    if title_type == 'graphic':
        title = get_object_or_404(GraphicTitle, id=title_id)
        bookmark = GraphicTitleBookmark.get_user_bookmark_for_title(request.user, title)
    elif title_type == 'text':
        title = get_object_or_404(TextTitle, id=title_id)

    # collect and update stats
    # metadata
    title.views_count = TitleView.get_views_count(title)
    title.favorites_count = TitleFavorite.get_favorite_count(title)
    title.save()
    is_favorite = TitleFavorite.get_favorite_status(title, request.user)
    tags = [relation.tag for relation in title.tags.all()]
    genres = [relation.tag_genre for relation in title.genres.all()]

    # ratings
    average_rate = TitleRating.get_average_rate(title)
    if request.user.is_authenticated:
        user_rate = title.ratings.filter(user=request.user).first()
    else:
        user_rate = 0
    user_rate = user_rate.rate if user_rate else 0
    rates_count = TitleRating.get_rates_count(title)
    star_rates_values = [(i, i + 1) for i in range(0, 5)]
    

    context = {
        'title': title,
        'user_favorite': is_favorite,
        'tags': tags,
        'genres': genres,
        'average_rate': average_rate,
        'rates_count': rates_count,
        'user_rate': user_rate,
        'star_rates_values': star_rates_values
    }

    return render(request, 'catalog/title_page_about.html', context)


def collect_chapters_section(request, title_type, title_id):
    """Creates context for chapters section of title's page"""
    assert title_type in ['text', 'graphic']

    if title_type == 'graphic':
        title = get_object_or_404(GraphicTitle, id=title_id)
        chapters = title.graphic_chapters.all()
        bookmark = GraphicTitleBookmark.get_user_bookmark_for_title(request.user, title)
    elif title_type == 'text':
        title = get_object_or_404(TextTitle, id=title_id)
        chapters = title.text_chapters.all()
        bookmark = TextTitleBookmark.get_user_bookmark_for_title(request.user, title)

    is_favorite = TitleFavorite.get_favorite_status(title, request.user)

    context = {
        'title': title,
        'chapters': chapters,
        'user_favorite': is_favorite,
        'bookmark': bookmark
    }

    return render(request, 'catalog/title_page_chapters.html', context)


def collect_comment_section(request, title_type, title_id):
    """Creates context for comment section of title's page"""
    assert title_type in ['text', 'graphic']

    if title_type == 'graphic':
        title = get_object_or_404(GraphicTitle, id=title_id)
    elif title_type == 'text':
        title = get_object_or_404(TextTitle, id=title_id)

    is_favorite = TitleFavorite.get_favorite_status(title, request.user)

    comments = title.comments.all()

    if request.method == 'POST':
        user = request.user
        text = request.POST.get('text')
        title.comments.create(text=text, user=user)
        return redirect_to_title_page(title_id, title.title_type, 'comments')

    comment_form = CommentForm()

    if title:
        context = {
            'title': title,
            'user_favorite': is_favorite,
            'comments': comments,
            'comment_form': comment_form
        }
    else:
        context = {}

    return render(request, 'catalog/title_page_comments.html', context)


def title_page_view(request, title_id=None):
    """Renders title page with specific context"""
    section = request.GET.get('section')
    title_type = request.GET.get('title_type')

    # collect context for different sections
    assert section in ['about', 'chapters', 'comments']

    if section == 'about':
        response = collect_about_section(request, title_type, title_id)
    elif section == 'chapters':
        response = collect_chapters_section(request, title_type, title_id)
    elif section == 'comments':
        response = collect_comment_section(request, title_type, title_id)

    return response


@login_required(login_url="users:login")
def change_favorite_title_status(request, title_id=None):
    """
    Changes 'favorite' status of title for users when they press the button
    on title page
    """
    title_type = request.GET.get('title_type')
    user = request.user

    assert title_type in ['text', 'graphic']

    if title_type == 'graphic':
        title = get_object_or_404(GraphicTitle, id=title_id)
    elif title_type == 'text':
        title = get_object_or_404(TextTitle, id=title_id)

    if TitleFavorite.get_favorite_status(title, user):
        user.remove_title_from_favorites(title)
        title.favorites.filter(user=user).delete()
    else:
        user.add_title_to_favorites(title)
        title.favorites.create(user=user)

    return redirect_to_title_page(title_id, title_type, request.GET.get('section'))

templates/catalog/home.html
<!-- Homepage of ABASlib -->
{% extends 'base.html' %}
{% load static %}
{% block title %}
  ABASlib — Главная
{% endblock %}

{% block styles %}
  <link rel="stylesheet" href="{% static 'css\catalog\home_styles.css' %}" />
{% endblock %}

{% block header %}
  <div class="button-group">
    {% if user.is_authenticated %}
      <div class="custom-select">
        <select name="redact_options" onchange="location = this.value" class="block-button">
          <option selected hidden disabled>Меню</option>
          <option value="{% url 'titles:upload_title' %}?title_type=text">Добавить тайтл (текст)</option>
          <option value="{% url 'titles:upload_title' %}?title_type=graphic">Добавить тайтл (графика)</option>
          {% block redact_options %}

          {% endblock %}
        </select>
      </div>
      <a id="profile-link" class="a-button block-button" href="{% url 'users:profile' %}">
        <img class="user-pic" src="{{ user.user_avatar.url }}" />
        {{ user.username }}
      </a>
      <a id="logout-link" class="a-button block-button" href="{% url 'users:logout' %}">
        <svg xmlns="http://www.w3.org/2000/svg" class="button-icon" fill="currentColor" class="bi bi-box-arrow-left" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M6 12.5a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v2a.5.5 0 0 1-1 0v-2A1.5 1.5 0 0 1 6.5 2h8A1.5 1.5 0 0 1 16 3.5v9a1.5 1.5 0 0 1-1.5 1.5h-8A1.5 1.5 0 0 1 5 12.5v-2a.5.5 0 0 1 1 0z" />
          <path fill-rule="evenodd" d="M.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L1.707 7.5H10.5a.5.5 0 0 1 0 1H1.707l2.147 2.146a.5.5 0 0 1-.708.708z" />
        </svg>Выход
      </a>
    {% else %}
      <a id="login-link" class="a-button block-button" href="{% url 'users:login' %}">
        <svg xmlns="http://www.w3.org/2000/svg" class="button-icon" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0z" />
          <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z" />
        </svg>Авторизация
      </a>
    {% endif %}
  </div>
{% endblock %}

{% block content %}
  <div class="container">
    <div id="main-content">
      <h1>ABASlib</h1>
      <hr />
      {% block titles %}
        <h4>Недавно добавлено</h4>
        <div class="titles">
          {% for title in new_titles %}
            <a title="{{ title.title_name_rus }}" class="title-card" href="{% url 'catalog:title_page' title.id %}?title_type={{ title.title_type }}&section=about">
              <img class="cover" src="{{ title.title_cover.url }}" alt="Здесь была обложка" />
              <div class="title-name">{{ title.title_name_rus }}</div>
            </a>
          {% endfor %}
        </div>
        <h4>Обновления</h4>
        <div class="titles">
          {% for title in updated_titles %}
            <a title="{{ title.title_name_rus }}" class="title-card" href="{% url 'catalog:title_page' title.id %}?title_type={{ title.title_type }}&section=about">
              <img class="cover" src="{{ title.title_cover.url }}" alt="Здесь была обложка" />
              <div class="title-name">{{ title.title_name_rus }}</div>
            </a>
          {% endfor %}
        </div>
      {% endblock %}
    </div>

    <div id="side">
      {% block sections %}
        <section>
          <h2>Разделы</h2>
          <a class="a-button block-button activated" href="{% url 'catalog:home' %}">Главная</a>
          <a class="a-button block-button" href="{% url 'catalog:all_titles' %}">Все тайтлы</a>
          <a class="a-button block-button" href="{% url 'catalog:text_titles' %}">Новеллы</a>
          <a class="a-button block-button" href="{% url 'catalog:graphic_titles' %}">Комиксы</a>
        </section>
      {% endblock %}
      
      {% block search %}
      
      {% endblock %}

    </div>
  </div>
{% endblock %}

templates/catalog/title_page_base.html
{% extends 'catalog/home.html' %}
{% load static %}
{% block title %}
  {{ title.title_name_rus }} — ABASlib
{% endblock %}

{% block styles %}
  <link rel="stylesheet" href="{% static 'css\catalog\title_page_styles.css' %}" />
  <link rel="stylesheet" href="{% static 'css\catalog\home_styles.css' %}" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
{% endblock %}

{% block redact_options %}
  <option value="{% url 'titles:upload_chapter' title.id %}?title_type={{ title.title_type }}">Добавить главу</option>
  <option value="{% url 'titles:update_title' title.id %}?title_type={{ title.title_type }}">Редактировать тайтл</option>
  <option value="{% url 'titles:delete_title' title.id %}?title_type={{ title.title_type }}">Удалить тайтл</option>
  {% if title.has_chapters %}
    <option value="{% url 'titles:delete_chapter' title.id %}?title_type={{ title.title_type }}">Удалить главу</option>
  {% endif %}
{% endblock %}

{% block content %}
  <div class="container">
    <div id="main-content">
      <div id="title-head">
        <img id="cover" src="{{ title.title_cover.url }}" alt="Тут была обложка" />
        <h2>{{ title.title_name_rus }} <br /> {{ title.title_name_eng }}</h2>
      </div>
      <div id="actions" class="button-group">
        <a id="like-button" class="a-button block-button action-button" href="{% url 'metadata:change_favorite_status' title.id %}?title_type={{ title.title_type }}&section={{ request.GET.section }}">
          {% if user_favorite %}
            <svg xmlns="http://www.w3.org/2000/svg" class="button-icon" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314" />
            </svg>В избранном
          {% else %}
            <svg xmlns="http://www.w3.org/2000/svg" class="button-icon" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
              <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143q.09.083.176.171a3 3 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15" />
            </svg>Добавить в избранное
          {% endif %}
        </a>

        {% if title.title_type == 'graphic' %}
          <a class="a-button block-button action-button" href="{% url 'reader:start_read_graphic' title.id %}">
            <svg xmlns="http://www.w3.org/2000/svg" class="button-icon" fill="currentColor" class="bi bi-book" viewBox="0 0 16 16">
              <path d="M1 2.828c.885-.37 2.154-.769 3.388-.893 1.33-.134 2.458.063 3.112.752v9.746c-.935-.53-2.12-.603-3.213-.493-1.18.12-2.37.461-3.287.811zm7.5-.141c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783" />
            </svg>Читать с начала
          </a>
        {% else %}
          <a class="a-button block-button action-button" href="{% url 'reader:start_read_text' title.id %}">
            <svg xmlns="http://www.w3.org/2000/svg" class="button-icon" fill="currentColor" class="bi bi-book" viewBox="0 0 16 16">
              <path d="M1 2.828c.885-.37 2.154-.769 3.388-.893 1.33-.134 2.458.063 3.112.752v9.746c-.935-.53-2.12-.603-3.213-.493-1.18.12-2.37.461-3.287.811zm7.5-.141c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783" />
            </svg>Читать с начала
          </a>
        {% endif %}
          <a class="a-button block-button action-button" href="{% url 'reader:open_bookmark' title.id %}?title_type={{ title.title_type }}">
            <svg xmlns="http://www.w3.org/2000/svg" class="button-icon" width="16" height="16" fill="currentColor" class="bi bi-book-half" viewBox="0 0 16 16">
              <path d="M8.5 2.687c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783"/>
            </svg>Продолжить чтение
          </a>
      </div>
    </div>
    <div id="side">      
      <div id="sections" class="button-group">
        {% block sections %}
          <a class="a-button block-button" href="{% url 'catalog:title_page' title.id %}?title_type={{ title.title_type }}&section=about">
            <svg xmlns="http://www.w3.org/2000/svg" class="button-icon" fill="currentColor" class="bi bi-info-square" viewBox="0 0 16 16">
              <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2z" />
              <path d="m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0" />
            </svg>О тайтле
          </a>
          <a class="a-button block-button" href="{% url 'catalog:title_page' title.id %}?title_type={{ title.title_type }}&section=chapters">
            <svg xmlns="http://www.w3.org/2000/svg" class="button-icon" fill="currentColor" class="bi bi-journal" viewBox="0 0 16 16">
              <path d="M3 0h10a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-1h1v1a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1v1H1V2a2 2 0 0 1 2-2" />
              <path d="M1 5v-.5a.5.5 0 0 1 1 0V5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1zm0 3v-.5a.5.5 0 0 1 1 0V8h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1zm0 3v-.5a.5.5 0 0 1 1 0v.5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1z" />
            </svg>Главы
          </a>
          <a class="a-button block-button" href="{% url 'catalog:title_page' title.id %}?title_type={{ title.title_type }}&section=comments">
            <svg xmlns="http://www.w3.org/2000/svg" class="button-icon" fill="currentColor" class="bi bi-chat-square-text" viewBox="0 0 16 16">
              <path d="M14 1a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1h-2.5a2 2 0 0 0-1.6.8L8 14.333 6.1 11.8a2 2 0 0 0-1.6-.8H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1zM2 0a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2.5a1 1 0 0 1 .8.4l1.9 2.533a1 1 0 0 0 1.6 0l1.9-2.533a1 1 0 0 1 .8-.4H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2z" />
              <path d="M3 3.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5M3 6a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9A.5.5 0 0 1 3 6m0 2.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5" />
            </svg>Комментарии
          </a>
        {% endblock %}
      </div>
      {% block section %}

      {% endblock %}
    </div>
  </div>
{% endblock %}